### ISSUE TITLE
User Story Attachment Download

### ISSUE THREAD

**Issue by avsreeraj** [lirantal/agilemanager-api#12]
Hi, 

If anyone wants to download user story attachments , they have to use the below REST URL.

**Attachment listing for a particular User Story**
https://agilemanager-xxxxxx.com/agm/api/workspaces/1000/backlog_items/4370/attachments/
https://agilemanager-xxxxxx.com/agm/api/workspaces/<WORKSPACE_ID>/backlog_items/<API_ID>/attachments/

> API_ID you can get from User Story details. 

**Listing a particular attachment for a User Story** 
https://agilemanager-xxxxxx.com/agm/api/workspaces/1000/backlog_items/4370/attachments/2918
https://agilemanager-xxxxxx.com/agm/api/workspaces/<WORKSPACE_ID>/backlog_items/<API_ID>/attachments/<ATTCHMENT_ID>

> API_ID you can get from User Story details. 

**Downloading a particular attachment for a User Story**
Here you need to pass an information with the request header.
_**headers.put("Accept", "application/octet-stream");**_
https://agilemanager-xxxxxx.com/agm/api/workspaces/1000/backlog_items/4370/attachments/2918
https://agilemanager-xxxxxx.com/agm/api/workspaces/<WORKSPACE_ID>/backlog_items/<API_ID>/attachments/<ATTCHMENT_ID>

> API_ID you can get from User Story details. 

![image](https://user-images.githubusercontent.com/29534176/35493168-633eea44-04d7-11e8-9f34-8587d809dbfe.png)

**Comment by lirantal** [comment]
This is great, thanks for sharing!
